@startuml


abstract class Joueur{
    # determinerTir(): Coordonnee
    + demanderTir(): Coordonnee
    + demanderPlacerBateau(numeroBateau: int): List<Coordonnee>
    # determinerPlacerBateau(coordonneBateau: List<Coordonnee>, numeroBateau: int)
}





class IADebutant {
    # determinerTir(): Coordonnee
}

class IAAvance{
    # determinerTir(): Coordonnee
}


class Personne {
    # determinerTir(): pair
    # determinerPlacerBateaux(coordonneBateau: List<Coordonnee>, numeroBateau: int>)
}



Joueur <|- Personne
Joueur <|-down- IADebutant
Joueur <|-down- IAAvance

@enduml
