@startuml


abstract class Joueur{
    # determinerTir(): pair
    + demanderTir(): pair
    + demanderPlacerBateaux(): List<List<Pair<Integer, Integer>>>
    # determinerPlacerBateaux(coordonneBateau: List<List<Pair<Integer, Integer>>>)
}





class IADebutant {
    # determinerTir(): pair
    # determinerPlacerBateaux(coordonneBateau: List<List<Pair<Integer, Integer>>>)
}

class IAAvance{
    # determinerTir(): pair
    # determinerPlacerBateaux(coordonneBateau: List<List<Pair<Integer, Integer>>>)
}


class Personne {
    # determinerTir(): pair
    # determinerPlacerBateaux(coordonneBateau: List<List<Pair<Integer, Integer>>>)
}



Joueur <|- Personne
Joueur <|-down- IADebutant
Joueur <|-down- IAAvance

@enduml