@startuml
hide footbox
mainframe Nouvelle Partie

actor Joueur_Main as joueur
participant MenuPrincipal

joueur -> MenuPrincipal : jouerNouvellePartie()
activate MenuPrincipal
activate joueur

create Jeu
MenuPrincipal -> Jeu : getInstance()
activate Jeu
MenuPrincipal <-- Jeu : instanceJeu
deactivate Jeu


MenuPrincipal -> Jeu : instanceJeu.jouer()
activate Jeu

@enduml