@startuml
hide footbox
mainframe Enregistrer Partie

actor Joueur_Main as joueur
participant Jeu
participant EnregistreurPartie


joueur -> Jeu : enregistrerPartie(nomFichier)
activate Jeu
Jeu -> EnregistreurPartie : enregistrerPartie(nomFichier)
activate EnregistreurPartie
Jeu <- EnregistreurPartie : getInstance()
Jeu --> EnregistreurPartie : instanceJeu

EnregistreurPartie -> EnregistreurPartie : Séréaliser Jeu en JSON
alt Fichier existe
    EnregistreurPartie -> EnregistreurPartie: Écraser fichier JSON
   else
   EnregistreurPartie -> EnregistreurPartie: Créer fichier JSON
end

EnregistreurPartie --> Jeu
deactivate EnregistreurPartie
Jeu --> joueur
deactivate Jeu

@enduml