@startuml
hide footbox
mainframe Charger Partie

actor Joueur_Main as joueur
participant MenuPrincipal
participant ChargeurPartie
participant Jeu

joueur -> MenuPrincipal : jouerPartieExistante(nomFichier)
activate MenuPrincipal
activate joueur

MenuPrincipal -> ChargeurPartie : chargerPartie(nomFichier)
activate ChargeurPartie

ChargeurPartie -> ChargeurPartie : Récupérer Fichier
ChargeurPartie -> ChargeurPartie : Lire Fichier
ChargeurPartie -> ChargeurPartie : Récupérer JSON

create Jeu
ChargeurPartie -> Jeu : getInstance()
activate Jeu
ChargeurPartie <-- Jeu : instanceJeu
deactivate Jeu
ChargeurPartie -> Jeu : chargerTirs(coordonnéesTirés)
activate Jeu
ChargeurPartie <-- Jeu
deactivate Jeu
ChargeurPartie --> MenuPrincipal : return Jeu
deactivate ChargeurPartie

MenuPrincipal -> Jeu : getInstance().jouer()
activate Jeu

@enduml
