stages:
  - build
  - test

build :
  image: maven:3.8.6-openjdk-18
  stage: build
  script:
    - mvn clean package

test:
  image: maven:3.8.6-openjdk-18
  stage: test
  script:
    - mvn clean package