@startuml
!pragma layout smetana
class PlateauFactory{
    + makePlateau(typePlateau : Plateau[], plateauBateau : PlateauBateau): Plateau
}

abstract class Plateau {
    # Plateau plateau
    + PlateauDecorator (plateau : Plateau)
    + ajouterTir ()
}


abstract class Joueur{
    # determinerTir(): pair
    + demanderPlacerBateaux()
    # determinerPlacerBateaux()
}

class MenuPrincipal{
    + {static} main(args: String[])
    + afficherMenu()
    - jouerNouvellePartie()
    - jouerPartieExistante(nomFichier: String)
    - quitterJeu()
}

class Jeu {
    - {static} instanceJeu: Jeu
    - Jeu()
    + {static} getInstance(): Jeu
    + chargerTirs(coordonnéesTirés: Liste<pair>)
    + jouer()
}

class PlateauBateau {
    + PlateauBateau (plateau : Plateau)
    + placerBateau()
    + ajouterTir ()
}

class PlateauTir {
    + PlateauTir (plateau : Plateau)
    - verifierTir(coordonnee: pair)
    + ajouterTir ()
}

class Bateau {
    - Position[]: pair
    - PointDeVie: int
    + estTouche(coordonnee: pair): Tir
}

enum Case {
    + aucun
    + rate
    + touche
    + coule
    + Bateau
}

class IADebutant {
    # determinerTir(): pair
}

class IAAvance{
    # determinerTir(): pair
}

class ChargeurPartie {
    + {static} chargerPartie(nomFichier: String)
}

class VisualiseurPartie {
    - timelinePlateaux [ ]
    + visualiserPartie(): pair<PlateauBateau,PlateauTir>
    + ajouterEtape(plateau : Plateau)
}

class AfficheurPartie {
    + {static} afficherPartie(plateauBat: PlateauBateau, plateauTir: PlateauTir)
}

class EnregistreurPartie {
    + {static} enregistrerPartie(nomFichier: String)
}

class Personne {
    # determinerTir(): pair
    # determinerPlacerBateaux(List<Coordonnee>, numeroBateau: int>)
}

PlateauBateau -- "5" Bateau
Plateau <|-- PlateauBateau
Plateau <|-- PlateauTir
Jeu *-left- "2" Joueur
Jeu -right-> EnregistreurPartie
Jeu -right-> VisualiseurPartie
Jeu -right-> AfficheurPartie
MenuPrincipal -> ChargeurPartie
MenuPrincipal ---> Jeu
Jeu --- "4" Plateau
Plateau -down- "*" Case
Joueur <|-up- IADebutant
Joueur <|-up- IAAvance
Joueur <|-left-- Personne
PlateauBateau <- PlateauTir
VisualiseurPartie --> AfficheurPartie
PlateauFactory -left-> Plateau
Jeu --  PlateauFactory
@enduml
