@startuml

[Joueur]

[Plateau]

[Bateau]

[Jeu]

[EnregistreurPartie]

[ChargeurPartie]

[AfficheurPartie]

[VisualiseurPartie]

[MenuPrincipal]

AjouterTir - [Plateau]
[Jeu] -> AjouterTir
EstTouche -- [Bateau]
[Plateau] --> EstTouche
DemanderTir -- [Joueur]
DemanderPlacerBateaux -left- [Joueur]
Jeu --> DemanderPlacerBateaux
Jeu -down-> DemanderTir

[EnregistreurPartie] -- EnregistrerPartie
EnregistrerPartie <-- [Jeu]
[ChargeurPartie] -up- ChargerPartie
[MenuPrincipal] --> ChargerPartie
[AfficheurPartie] -left- AfficherPartie
Jeu -> AfficherPartie
[VisualiseurPartie] -left- VisualiserPartie
[VisualiseurPartie] -> AfficherPartie
[Jeu] -> VisualiserPartie
[Jeu] -left- Jouer
[MenuPrincipal] -> Jouer

@enduml