@startuml

hide footbox

mainframe Choisir Case

participant MenuPrincipal
participant Jeu as jeu
participant Joueur as j
participant PlateauTir as pt
participant PlateauBateau as pb
MenuPrincipal -> jeu : new
activate jeu
MenuPrincipal -> jeu : jouer()
jeu -> pt : new
activate pt
pt -> pt : new [][] caseMatricePT
jeu -> pb : new
activate pb
pb -> pb : new [][] caseMatricePB
jeu -> j : demanderTir(S)
j --> jeu : coordonnees_pair
jeu -> pt : ajouterTir(coordonnee: pair)
pt -> pt : verifierTir(coordonnee: pair)
pt -> pb : validerCase()
pb -> pb : majCase()
pb --> pt : reponse
pt -> pt : majCase()

@enduml
