@startuml
hide footbox
mainframe Placer navire

actor Joueur_Main as joueur
participant "jeu: Jeu" as Jeu
participant "plateauBat: PlateauBateau" as platBat
participant "afficheur: AfficheurPartie" as AfficheurPartie



loop tant qu'il reste des bateaux a placer
joueur -> Jeu : demanderPlacerBateau()
activate joueur
activate Jeu
Jeu -> Jeu : actualiserPlateaux(coordonnees, plateauBateau)
Jeu -> platBat : placerBateau()
Jeu -> AfficheurPartie : afficherPartie(plateauBat, plateauTir)
activate AfficheurPartie
AfficheurPartie -> AfficheurPartie: Afficher Plateaux
AfficheurPartie --> Jeu
deactivate AfficheurPartie
end

@enduml