@startuml
hide footbox
mainframe Tirer

actor Joueur_Main as joueur
participant "jeu: Jeu" as Jeu
participant "plateauBat: PlateauBateau" as platBat
participant "plateauTir: PlateauTir" as platTir
participant "afficheur: AfficheurPartie" as AfficheurPartie



Jeu -> joueur : demanderTir()
activate joueur
activate Jeu
joueur --> Jeu : coordonnees
Jeu -> Jeu : actualiserPlateaux(coordonnees, plateauBateau)
Jeu -> platTir : ajouterTir(coordonnee)
activate platTir
platTir -> platTir : verifierTir(coordonnee)
platTir -> platBat : verifierCase
deactivate platTir
Jeu -> AfficheurPartie: afficherPartie(plateauBat, plateauTir)
activate AfficheurPartie
AfficheurPartie -> AfficheurPartie: Afficher Plateaux
AfficheurPartie --> Jeu
deactivate AfficheurPartie
Jeu -> Jeu: determinerGagnant()
alt Tous les bateaux de l'adversaire ont coulé
Jeu --> joueur: Il est le gagnant de la partie
else
Jeu -> Jeu: effectuerProchainTour()

end

@enduml